-- Habilitar la creación de usuarios locales en PDB
ALTER SESSION SET CONTAINER=FREEPDB1;

-- Crear esquemas para cada microservicio
CREATE USER INVENTARIO_DB IDENTIFIED BY SmartLogix123;
GRANT ALL PRIVILEGES TO INVENTARIO_DB;

CREATE USER PEDIDO_DB IDENTIFIED BY SmartLogix123;
GRANT ALL PRIVILEGES TO PEDIDO_DB;

CREATE USER ENVIO_DB IDENTIFIED BY SmartLogix123;
GRANT ALL PRIVILEGES TO ENVIO_DB;

CREATE USER USUARIO_DB IDENTIFIED BY SmartLogix123;
GRANT ALL PRIVILEGES TO USUARIO_DB;