# Configuración del Servidor
server.port=8080
spring.application.name=api-gateway

# Configuración de Rutas del Gateway
# Ruta para Pedidos
spring.cloud.gateway.routes[0].id=pedido-service
spring.cloud.gateway.routes[0].uri=lb://PEDIDO-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/pedidos/**

# Ruta para Inventario
spring.cloud.gateway.routes[1].id=inventario-service
spring.cloud.gateway.routes[1].uri=lb://INVENTARIO-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/inventario/**

# Ruta para Envio
spring.cloud.gateway.routes[2].id=envio-service
spring.cloud.gateway.routes[2].uri=lb://ENVIO-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/envio/**

# Registro en Discovery (Eureka por ejemplo)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/